/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/Contact'
import { Route as AboutRouteImport } from './routes/About'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewPortfolioIdRouteImport } from './routes/preview.$portfolioId'
import { Route as BuilderPortfolioIdRouteImport } from './routes/builder.$portfolioId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthRegisterRouteImport } from './routes/auth/Register'
import { Route as AuthLoginRouteImport } from './routes/auth/Login'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/Contact',
  path: '/Contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/About',
  path: '/About',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewPortfolioIdRoute = PreviewPortfolioIdRouteImport.update({
  id: '/preview/$portfolioId',
  path: '/preview/$portfolioId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderPortfolioIdRoute = BuilderPortfolioIdRouteImport.update({
  id: '/builder/$portfolioId',
  path: '/builder/$portfolioId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/Register',
  path: '/auth/Register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/Login',
  path: '/auth/Login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/About': typeof AboutRoute
  '/Contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/auth/Login': typeof AuthLoginRoute
  '/auth/Register': typeof AuthRegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/builder/$portfolioId': typeof BuilderPortfolioIdRoute
  '/preview/$portfolioId': typeof PreviewPortfolioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/About': typeof AboutRoute
  '/Contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/auth/Login': typeof AuthLoginRoute
  '/auth/Register': typeof AuthRegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/builder/$portfolioId': typeof BuilderPortfolioIdRoute
  '/preview/$portfolioId': typeof PreviewPortfolioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/About': typeof AboutRoute
  '/Contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/auth/Login': typeof AuthLoginRoute
  '/auth/Register': typeof AuthRegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/builder/$portfolioId': typeof BuilderPortfolioIdRoute
  '/preview/$portfolioId': typeof PreviewPortfolioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/About'
    | '/Contact'
    | '/dashboard'
    | '/auth/Login'
    | '/auth/Register'
    | '/auth/callback'
    | '/builder/$portfolioId'
    | '/preview/$portfolioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/About'
    | '/Contact'
    | '/dashboard'
    | '/auth/Login'
    | '/auth/Register'
    | '/auth/callback'
    | '/builder/$portfolioId'
    | '/preview/$portfolioId'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/About'
    | '/Contact'
    | '/dashboard'
    | '/auth/Login'
    | '/auth/Register'
    | '/auth/callback'
    | '/builder/$portfolioId'
    | '/preview/$portfolioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BuilderPortfolioIdRoute: typeof BuilderPortfolioIdRoute
  PreviewPortfolioIdRoute: typeof PreviewPortfolioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Contact': {
      id: '/Contact'
      path: '/Contact'
      fullPath: '/Contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/About': {
      id: '/About'
      path: '/About'
      fullPath: '/About'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$portfolioId': {
      id: '/preview/$portfolioId'
      path: '/preview/$portfolioId'
      fullPath: '/preview/$portfolioId'
      preLoaderRoute: typeof PreviewPortfolioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$portfolioId': {
      id: '/builder/$portfolioId'
      path: '/builder/$portfolioId'
      fullPath: '/builder/$portfolioId'
      preLoaderRoute: typeof BuilderPortfolioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/Register': {
      id: '/auth/Register'
      path: '/auth/Register'
      fullPath: '/auth/Register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/Login': {
      id: '/auth/Login'
      path: '/auth/Login'
      fullPath: '/auth/Login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BuilderPortfolioIdRoute: BuilderPortfolioIdRoute,
  PreviewPortfolioIdRoute: PreviewPortfolioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
